@echo off
setlocal

echo Checking Android SDK and Gradle...
powershell -ExecutionPolicy Bypass -File "%~dp0setup_sdk.ps1"

if errorlevel 1 (
    echo Failed to setup SDK/Gradle.
    exit /b 1
)

:: Load environment variables generated by PowerShell script
if exist "%~dp0env_setup.bat" (
    call "%~dp0env_setup.bat"
) else (
    echo Error: env_setup.bat not found!
    exit /b 1
)

echo Building Debug APK...

:: We now use 'gradle' directly since we installed it
call gradle assembleDebug

if errorlevel 1 goto :error
echo Build Initialized (Skeleton).
exit /b 0

:error
echo Build Failed.
exit /b 1
